<?php

namespace EuroLiterie\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepo extends EntityRepository
{
}
