<?php

namespace EuroLiterie\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepo extends EntityRepository
{
    public function getHtml()
    {
        return '<div class="admin-c border">
                    <input type="hidden" value="%idMarque%">
                    <section class="contentMarque">
                        <article class="adminMarque">
                            <label>Nom :</label><input type="text" value="%nomMarque%">
                            <label>Texte :</label><textarea >%content%</textarea>
                            <label>Lien :</label><input type="text" value="%marqueLien%">
                        </article>
                        <article class="adminLogoMarque">
                            <label>Logo :</label><figure class="marque-img"><img src="../../bundles/EuroLiteriestructure/images/marques/%pngUrl%"></img></figure>
                            <section class="btn-logo">
                                <li>Modifier</li>
                            </section>
                        </article>
                    </section>
                        <article class="btn-admin">
                        <li>Mettre à jour</li>
                        </article>
                        <article class="btn-admin">
                            <li>Supprimer</li>
                        </article>
                </div>';
    }
}
