<?php

namespace Yomaah\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * articleRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepo extends EntityRepository
{
    public function findByPage($pageUrl)
    {
        $query = $this->getEntityManager()->createQuery('select a, p from yomaahBundle:Article a join a.page p where p.pageUrl = :url')->setParameter('url',$pageUrl);
        return $query->getResult();
    }
}
