<?php

namespace Yomaah\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * articleRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepo extends EntityRepository
{
}
