<?php

namespace Yomaah\structureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepo
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepo extends EntityRepository
{
    public function get($page)
    {
        $query = $this->_em->createQuery('select p.pageId from yomaahBundle:Page p where p.pageUrl = :url')->setParameter('url',$page);
        $id = $query->getSingleResult();
        $page = new Page();
        $page->setPageId($id['pageId'])->setPageUrl($page);
        return $page;
        //return $query->getResult();
    }
}
